### ISSUE TITLE
Event checklist!

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#15]
@brenna came up with the idea of a simple checklist to run through maybe the week before an event. This could be used as a template for each event?!

Thought I would get it started so we don't forget about it. Add to it anything that is missing!
- [ ] email notification, as soon as event is confirmed 
- [ ] Email Reminder, few days before
- [ ] Twitter Reminder, few days before
- [ ] Mentor roll call.
- [ ] Coffee order for event.
- [ ] Update main Node School Site, and Node School Toronto Site

**Comment by vladikoff** [comment]
Need to update the main Node School and the Node School Toronto websites

**Comment by Rchristiani** [comment]
Updated list.

Also I think some language around "Bring your own laptop" should be put up on the site. A couple people have come with no laptop..

**Comment by vladikoff** [comment]
> Also I think some language around "Bring your own laptop" should be put up on the site.

 plus try to install node. good suggestion

**Comment by brenna** [comment]
@Rchristiani @vladikoff I believe the event page and/or reminder email typically include both those instructions but let's make something like "what to expect at NodeSchool"  a permanent fixture on our site. I'll add a new issue for it.

**Comment by brenna** [comment]
also added sending out email notification to all subscribers to announce the event.

**Comment by Rchristiani** [comment]
Closing since I started a checklist for September.
