### ISSUE TITLE
September Event Checklist

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#17]
Won't be there, but starting a checklist since it is good to start thinking about these things now.
- [x] Email notification, as soon as event is confirmed.
- [x] Tweet as soon as event is confirmed.
- [x] Email Reminder, few days before.
- [ ] Twitter Reminder, few days before.
- [x] Mentor roll call.
- [x] Coffee order for event.
- [x] Update main Node School Site, and Node School Toronto Site
- [x] buy more nodeSchool stickers

**Comment by andrewdamelio** [comment]
added stickers - i think we are out, i can order more

**Comment by Rchristiani** [comment]
@andrewdamelio let me know how much sticker are, I will throw in a few bucks!

**Comment by darcyclarke** [comment]
This also looked helpful: https://github.com/nodeschool/organizers/wiki/Checklist-For-Events

**Comment by richgilbank** [comment]
Forgot to update this - @andrewdamelio you mentioned you ordered more stickers, right?

**Comment by richgilbank** [comment]
Roll call so far: 
- Tessa
- Travis
- Ahmad
- Ricky
- Jeff
- Rich
- Ryan
- Andrew
- Darcy
- Vlad

**Comment by andrewdamelio** [comment]
@richgilbank :stars: stickers acquired!

**Comment by richgilbank** [comment]
![](https://camo.githubusercontent.com/7fcb80a72e78504df1eb745bd2c673b70258e640/687474703a2f2f692e67697068792e636f6d2f57584f733348766155773148692e676966)

**Comment by darcyclarke** [comment]
I'm in for the 26th

**Comment by vladikoff** [comment]
> Roll call so far: 

I'll be there!
