### ISSUE TITLE
November 21st Checklist

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#25]
- [x] Date: November 21st?
- [x] Location
- [x] Create invite for event
- [x] Schedule Tweets
  - [x] Tweet as soon as event is confirmed.
  - [x] Tweet ticket link when available
  - [x] Twitter Reminder, few days before.
- [x] Schedule Emails
  - [x] Email notification, as soon as event is confirmed.
  - [x] Email Reminder, few days before.
- [x] Mentor roll call
- [x] Coffee order for event.
- [x] Site Updates
  - [x] Update main Node School Site
  - [x] Update Node School Toronto Site
- [ ] NodeSchool stickers?
- [x] Get 2-3 people to do small talks.

**Comment by Rchristiani** [comment]
Able to mentor and do a small talk about nodebots!

**Comment by brenna** [comment]
@Rchristiani we're looking at Nov 21st right?

**Comment by Rchristiani** [comment]
@brenna Yes, forgot to add that.

**Comment by Fishrock123** [comment]
Able to mentor. Thinking about the talk thing.

**Comment by darcyclarke** [comment]
I'm in for November :+1:

**Comment by brenna** [comment]
I'm available to mentor too. 

Shall I wait on tweeting until we confirm a location?

**Comment by Rchristiani** [comment]
Nice!

I was going to check with @richgilbank by the end of the week if we are good for shopify. So maybe a tweet on Friday?

**Comment by brenna** [comment]
:cool: Good plan.

**Comment by Rchristiani** [comment]
@brenna Location confirmed. Tweet away!

**Comment by brenna** [comment]
Thanks @Rchristiani, done. Will tweet again once we get tickets set up.

**Comment by jeffjewiss** [comment]
I've updated the site and submitted the event to the main site/map as well as sent out the first reminder emial.

@Rchristiani do you mind scheduling a tweet for a few days before?

**Comment by Rchristiani** [comment]
@jeffjewiss Already thinking about it! Will do! :+1:

**Comment by Rchristiani** [comment]
Great event!
