### ISSUE TITLE
December 12th Checklist

### ISSUE THREAD

**Issue by jeffjewiss** [nodeschool/toronto#37]
- [x] Create invite for event
- [x] Schedule Tweets
  - [x] Tweet as soon as event is confirmed.
  - [x] Tweet ticket link when available
  - [x] Twitter Reminder, few days before.
- [ ] Schedule Emails
  - [x] Email notification, as soon as event is confirmed.
  - [ ] Email Reminder, few days before.
- [x] Mentor roll call
- [x] Coffee order for event.
- [x] Site Updates
  - [x] Update main Node School Site
  - [x] Update Node School Toronto Site
- [x] NodeSchool stickers?
- [x] Get 2-3 people to do small talks.

**Comment by Rchristiani** [comment]
Talks are Ricky and Darcy so far.

**Comment by darcyclarke** [comment]
NodeSchool Site is updated: http://nodeschool.io/events
