### ISSUE TITLE
February Checklist

### ISSUE THREAD

**Issue by Rchristiani** [nodeschool/toronto#55]
A little late on this, but better late than never.
- [x] Create invite for event
- [x] Schedule Tweets
  - [x] Tweet as soon as event is confirmed.
  - [x] Tweet ticket link when available
  - [ ] Twitter Reminder, few days before.
- [ ] Schedule Emails
  - [x] Email notification, as soon as event is confirmed.
  - [ ] Email Reminder, few days before.
- [x] Mentor roll call
- [ ] Coffee order for event.
- [x] Site Updates
  - [x] Update main Node School Site
  - [x] Update Node School Toronto Site
- [x] NodeSchool stickers?
- [ ] Get 2-3 people to do small talks.

**Comment by Rchristiani** [comment]
I will do a talk on Spread and Rest in ES6.

**Comment by vladikoff** [comment]
Is it possible to add the event to http://nodeschool.io/ calendar?

**Comment by richgilbank** [comment]
@vladikoff done!

**Comment by vladikoff** [comment]
awwww yiisssss!
